version: '3.8'

services:
  prometheus:
    image: prom/prometheus:latest
    user: "$UID:$GID"
    container_name: prometheus
    volumes:
      - ./prometheus/config.yml:/etc/prometheus/prometheus.yml
      - ~/docker/volumes/prometheus:/prometheus
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
  prometheus-auth:
    image: nginx:latest
    container_name: prometheus-auth
    ports:
      - 9090:80
    volumes:
      - ./prometheus/nginx.conf:/etc/nginx/nginx.conf
      - ./prometheus/.htpasswd:/etc/nginx/.htpasswd

  grafana:
    image: grafana/grafana:latest
    user: "$UID:$GID"
    container_name: grafana
    ports:
      - "3000:3000"
    volumes:
      - ~/docker/volumes/grafana:/var/lib/grafana
  
  # loki:
  #   image: grafana/loki:2.0.0
  #   container_name: loki
  #   command:
  #     - -config.file=/etc/loki/local-config.yaml
  #     - -print-config-stderr=true