global:
  resolve_timeout: 1m

route:
  receiver: "mail"
  group_by: ["alertname"]
  repeat_interval: 4h

receivers:
  - name: "mail"
    email_configs:
      - smarthost: "smtp.gmail.com:587"
        auth_username: "no-reply@sidekick-coder.com"
        auth_identity: "no-reply@sidekick-coder.com"
        auth_password: "password"
        from: "no-reply@sidekick-coder.com"
        to: "henrique@sidekick-coder.com"
        tls_config:
          insecure_skip_verify: true
