version: '3.8'

services:
  alertmanager:
    image: prom/alertmanager:v0.24.0
    container_name: alertmanager
    user: "$UID:$GID"
    restart: unless-stopped
    volumes:
      - $PWD/alertmanager/config.yml:/alertmanager/alertmanager.yml
    command:
            - '--config.file=/alertmanager/alertmanager.yml'
  
  auth:
    image: nginx:latest
    container_name: alertmanager-auth
    restart: unless-stopped
    ports:
      - 9093:80
    volumes:
      - $PWD/alertmanager/nginx.conf:/etc/nginx/nginx.conf
      - $PWD/alertmanager/.htpasswd:/etc/nginx/.htpasswd