version: '3.8'

services:
  grafana:
    image: grafana/grafana:latest
    user: "$UID:$GID"
    container_name: grafana
    restart: unless-stopped
    ports:
      - "3000:3000"
    volumes:
      - $PWD/.volumes/grafana:/var/lib/grafana