version: '3.8'

services:
  promtail:
    image: grafana/promtail:2.6.1
    container_name: promtail
    restart: unless-stopped
    volumes:
      - $PWD/promtail/config.yml:/etc/promtail/config.yml
      - /var/log:/var/log:ro
  
  auth:
    image: nginx:latest
    container_name: promtail-auth
    restart: unless-stopped
    ports:
      - 9080:80
    volumes:
      - $PWD/promtail/nginx.conf:/etc/nginx/nginx.conf
      - $PWD/promtail/.htpasswd:/etc/nginx/.htpasswd