# docker-compose base for node_exporter
version: "3"

services:
  node_exporter:
    image: prom/node-exporter:latest
    user: "$UID:$GID"
    container_name: node_exporter
    restart: unless-stopped
    command:
      - "--path.rootfs=/host"
    pid: host
    volumes:
      - "/:/host:ro,rslave"
