version: '3.8'

services:
  alertmanager:
    extends:
      file: alertmanager/docker-compose.yml
      service: alertmanager

  alertmanager_auth:
    extends:
      file: alertmanager/docker-compose.yml
      service: auth

  loki:
    extends:
      file: loki/docker-compose.yml
      service: loki

  loki_auth:
    extends:
      file: loki/docker-compose.yml
      service: auth
  
  node_exporter:
    extends:
      file: node_exporter/docker-compose.yml
      service: node_exporter
  
  node_exporter_auth:
    extends:
      file: node_exporter/docker-compose.yml
      service: auth
  
  prometheus:
    extends:
      file: prometheus/docker-compose.yml
      service: prometheus
  
  prometheus_auth:
    extends:
      file: prometheus/docker-compose.yml
      service: auth
  
  promtail:
    extends:
      file: promtail/docker-compose.yml
      service: promtail
  
  promtail-auth:
    extends:
      file: promtail/docker-compose.yml
      service: auth
  
  grafana:
    extends:
      file: grafana/docker-compose.yml
      service: grafana
  
  