version: '3.8'

services:
  loki:
    image: grafana/loki:2.6.1
    container_name: loki
    user: "$UID:$GID"
    restart: unless-stopped
    volumes:
      - $PWD/loki/config.yml:/etc/config/loki.yml
    command:
      - -config.file=/etc/config/loki.yml
      - -print-config-stderr=true
  
  auth:
    image: nginx:latest
    container_name: loki_auth
    restart: unless-stopped
    ports:
      - 3100:80
    volumes:
      - $PWD/loki/nginx.conf:/etc/nginx/nginx.conf
      - $PWD/loki/.htpasswd:/etc/nginx/.htpasswd