version: '3.8'

services:
  prometheus:
    image: prom/prometheus:latest
    user: "$UID:$GID"
    container_name: prometheus
    restart: unless-stopped
    volumes:
      - $PWD/prometheus/config.yml:/etc/prometheus/prometheus.yml
      - $PWD/.volumes/prometheus:/prometheus
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
  
  auth:
    image: nginx:latest
    container_name: prometheus-auth
    restart: unless-stopped
    ports:
      - 9090:80
    volumes:
      - $PWD/prometheus/nginx.conf:/etc/nginx/nginx.conf
      - $PWD/prometheus/.htpasswd:/etc/nginx/.htpasswd